name: TunderePortMapper
main: net.tsuttsu305.tundereportmapper.TunderePortMapper
version: 1.0.0
author: tsuttsu305
commands:
  port:
    description: PortCommand
    permission: port.admin
    usage: /port <open | close>
permissions:
  port.admin:
    default: OP